### ISSUE TITLE
ResourceApps: type of Owners field is inconsistent

### ISSUE THREAD

**Issue by philband** [Cloud-Architekt/EntraOps#31]
Depending on the number of Owners on an SPN, the Owners field output of EntraOps changes:
* zero Owners `[]`(empty array)
* one Owner `owner-object-guid` (string with single owner object GUID)
* more than  one Owner `["object-guid-1", "object-guid-2"]` (array of owner object GUIDs)

This leads to problems parsing the EntraOps output in strictly-typed languages.

**Comment by Cloud-Architekt** [comment]
Thanks for the feedback, @philband.
Issue has been fixed in release 0.3.4 which has been published today.
I have checked all multi value fields to make sure that we've always a array with owner object GUIDs.
In case of empty ownership there will be an empty array instead of $null.

Don't hesitate to reach out if you see any other concerns or issues.
